name: Meu teste de deploy

on: 
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checker o codigo
        uses: actions/checkout@v4
        
      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5
       
      - name: upload do site
        uses: actions/upload-pages-artifact@v3
        with:
           path: .

      - name: Publicar do GitHub Pages
        uses: actions/deploy-pages@v4
        
          